name: CMake (wasm32)
on: [push, pull_request]
env:
  TERM: xterm-256color
  GTEST_COLOR: 1
jobs:
  cmake-emscripten:
    name: Emscripten
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Emscripten
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
        source ./emsdk_env.sh
        echo "${PATH}" > $GITHUB_PATH
        echo "EMSDK=${EMSDK}" >> $GITHUB_ENV
        echo "EM_CONFIG=${EM_CONFIG}" >> $GITHUB_ENV
        echo "EM_CACHE=${EM_CACHE}" >> $GITHUB_ENV
        echo "EMSDK_NODE=${EMSDK_NODE}" >> $GITHUB_ENV

    - name: Generate project files
      # Shared libaries turned off for Emscripten
      run: |
        cmake . \
          -DZLIB_COMPAT=ON \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_SHARED_LIBS=OFF \
          -DWITH_MAINTAINER_WARNINGS=ON \
          -DCMAKE_C_COMPILER_TARGET=wasm32 \
          -DCMAKE_TOOLCHAIN_FILE=${EMSDK}/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake \
          -DCMAKE_CROSSCOMPILING_EMULATOR=${EMSDK_NODE}
      env:
        CI: true

    - name: Compile source code
      run: cmake --build . --config Release

    - name: Run test cases
      run: ctest --verbose -C Release --output-on-failure --max-width 120 -j 6
